package game.map;

public enum Constructable {
    AQUEDUCT, ARCHERYRANGE, BARRACKS, CITY, DOCK, FARM, LUMBERMILL, MINE, ROAD, STABLE, TOWER, WHEAT, WORKSHOP,
    ARCHER, BUILDER, CATAPULT, KNIGHT, SETTLER, SWORDSMAN
}
